/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppWWorkspaceIdRouteImport } from './routes/_app.w.$workspaceId'
import { Route as AppWWorkspaceIdIndexRouteImport } from './routes/_app.w.$workspaceId.index'
import { Route as AppWWorkspaceIdGraphRouteImport } from './routes/_app.w.$workspaceId.graph'
import { Route as AppWWorkspaceIdPNodeIdRouteImport } from './routes/_app.w.$workspaceId.p.$nodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWWorkspaceIdRoute = AppWWorkspaceIdRouteImport.update({
  id: '/w/$workspaceId',
  path: '/w/$workspaceId',
  getParentRoute: () => AppRoute,
} as any)
const AppWWorkspaceIdIndexRoute = AppWWorkspaceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWWorkspaceIdRoute,
} as any)
const AppWWorkspaceIdGraphRoute = AppWWorkspaceIdGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => AppWWorkspaceIdRoute,
} as any)
const AppWWorkspaceIdPNodeIdRoute = AppWWorkspaceIdPNodeIdRouteImport.update({
  id: '/p/$nodeId',
  path: '/p/$nodeId',
  getParentRoute: () => AppWWorkspaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdRouteWithChildren
  '/w/$workspaceId/graph': typeof AppWWorkspaceIdGraphRoute
  '/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$nodeId': typeof AppWWorkspaceIdPNodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/w/$workspaceId/graph': typeof AppWWorkspaceIdGraphRoute
  '/w/$workspaceId': typeof AppWWorkspaceIdIndexRoute
  '/w/$workspaceId/p/$nodeId': typeof AppWWorkspaceIdPNodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_app/w/$workspaceId': typeof AppWWorkspaceIdRouteWithChildren
  '/_app/w/$workspaceId/graph': typeof AppWWorkspaceIdGraphRoute
  '/_app/w/$workspaceId/': typeof AppWWorkspaceIdIndexRoute
  '/_app/w/$workspaceId/p/$nodeId': typeof AppWWorkspaceIdPNodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/w/$workspaceId'
    | '/w/$workspaceId/graph'
    | '/w/$workspaceId/'
    | '/w/$workspaceId/p/$nodeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/w/$workspaceId/graph'
    | '/w/$workspaceId'
    | '/w/$workspaceId/p/$nodeId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/register'
    | '/_app/w/$workspaceId'
    | '/_app/w/$workspaceId/graph'
    | '/_app/w/$workspaceId/'
    | '/_app/w/$workspaceId/p/$nodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/w/$workspaceId': {
      id: '/_app/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/w/$workspaceId'
      preLoaderRoute: typeof AppWWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/w/$workspaceId/': {
      id: '/_app/w/$workspaceId/'
      path: '/'
      fullPath: '/w/$workspaceId/'
      preLoaderRoute: typeof AppWWorkspaceIdIndexRouteImport
      parentRoute: typeof AppWWorkspaceIdRoute
    }
    '/_app/w/$workspaceId/graph': {
      id: '/_app/w/$workspaceId/graph'
      path: '/graph'
      fullPath: '/w/$workspaceId/graph'
      preLoaderRoute: typeof AppWWorkspaceIdGraphRouteImport
      parentRoute: typeof AppWWorkspaceIdRoute
    }
    '/_app/w/$workspaceId/p/$nodeId': {
      id: '/_app/w/$workspaceId/p/$nodeId'
      path: '/p/$nodeId'
      fullPath: '/w/$workspaceId/p/$nodeId'
      preLoaderRoute: typeof AppWWorkspaceIdPNodeIdRouteImport
      parentRoute: typeof AppWWorkspaceIdRoute
    }
  }
}

interface AppWWorkspaceIdRouteChildren {
  AppWWorkspaceIdGraphRoute: typeof AppWWorkspaceIdGraphRoute
  AppWWorkspaceIdIndexRoute: typeof AppWWorkspaceIdIndexRoute
  AppWWorkspaceIdPNodeIdRoute: typeof AppWWorkspaceIdPNodeIdRoute
}

const AppWWorkspaceIdRouteChildren: AppWWorkspaceIdRouteChildren = {
  AppWWorkspaceIdGraphRoute: AppWWorkspaceIdGraphRoute,
  AppWWorkspaceIdIndexRoute: AppWWorkspaceIdIndexRoute,
  AppWWorkspaceIdPNodeIdRoute: AppWWorkspaceIdPNodeIdRoute,
}

const AppWWorkspaceIdRouteWithChildren = AppWWorkspaceIdRoute._addFileChildren(
  AppWWorkspaceIdRouteChildren,
)

interface AppRouteChildren {
  AppWWorkspaceIdRoute: typeof AppWWorkspaceIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppWWorkspaceIdRoute: AppWWorkspaceIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
