// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nook.Domain.Enums;
using Nook.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Nook.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914202524_Wave2Collections")]
    partial class Wave2Collections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "link_kind", new[] { "embed", "mention", "relation", "synced", "url", "wikilink" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "node_kind", new[] { "collection_row", "database", "file", "folder", "page" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "snapshot_kind", new[] { "auto", "manual", "pre_restore" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "tag_source", new[] { "inline", "manual" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "workspace_role", new[] { "editor", "owner", "viewer" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nook.Domain.Entities.Alias", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("Value")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("alias");

                    b.HasKey("NodeId", "Value")
                        .HasName("pk_aliases");

                    b.HasIndex("Value")
                        .HasDatabaseName("ix_aliases_alias_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Value"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Value"), new[] { "gin_trgm_ops" });

                    b.ToTable("aliases", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_api_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_api_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_api_tokens_user_id");

                    b.ToTable("api_tokens", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BlobSha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("blob_sha");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("block_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedText")
                        .HasColumnType("text")
                        .HasColumnName("extracted_text");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("filename");

                    b.Property<JsonElement?>("Meta")
                        .HasColumnType("jsonb")
                        .HasColumnName("meta");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<string>("PropertyId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("property_id");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("content")
                        .HasColumnName("purpose");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<NpgsqlTsVector>("text_en")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("text_en")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(extracted_text, ''))", true);

                    b.Property<NpgsqlTsVector>("text_ru")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("text_ru")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(extracted_text, ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.HasIndex("BlobSha")
                        .HasDatabaseName("ix_attachments_blob_sha");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_attachments_node_id");

                    b.HasIndex("text_en")
                        .HasDatabaseName("ix_attachments_text_en");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("text_en"), "gin");

                    b.HasIndex("text_ru")
                        .HasDatabaseName("ix_attachments_text_ru");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("text_ru"), "gin");

                    b.HasIndex("WorkspaceId", "NodeId")
                        .HasDatabaseName("ix_attachments_workspace_id_node_id");

                    b.ToTable("attachments", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Blob", b =>
                {
                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<string>("Mime")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("mime");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTimeOffset>("StoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stored_at");

                    b.HasKey("Sha256")
                        .HasName("pk_blobs");

                    b.ToTable("blobs", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<JsonElement?>("Content")
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid?>("ParentBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_block_id");

                    b.Property<string>("PlainText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("plain_text");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<JsonElement>("Props")
                        .HasColumnType("jsonb")
                        .HasColumnName("props");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<NpgsqlTsVector>("text_en")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("text_en")
                        .HasComputedColumnSql("to_tsvector('english', coalesce(plain_text, ''))", true);

                    b.Property<NpgsqlTsVector>("text_ru")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("text_ru")
                        .HasComputedColumnSql("to_tsvector('russian', coalesce(plain_text, ''))", true);

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("text_en")
                        .HasDatabaseName("ix_blocks_text_en");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("text_en"), "gin");

                    b.HasIndex("text_ru")
                        .HasDatabaseName("ix_blocks_text_ru");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("text_ru"), "gin");

                    b.HasIndex("NodeId", "ParentBlockId", "Position")
                        .HasDatabaseName("ix_blocks_node_id_parent_block_id_position");

                    b.ToTable("blocks", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<JsonElement>("PropertySchema")
                        .HasColumnType("jsonb")
                        .HasColumnName("property_schema");

                    b.Property<JsonElement>("RowLayout")
                        .HasColumnType("jsonb")
                        .HasColumnName("row_layout");

                    b.Property<JsonElement>("Templates")
                        .HasColumnType("jsonb")
                        .HasColumnName("templates");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("WorkspaceId", "Name")
                        .HasDatabaseName("ix_collections_workspace_id_name");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.CollectionView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<JsonElement>("Config")
                        .HasColumnType("jsonb")
                        .HasColumnName("config");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DatabaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("database_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("position");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_collection_views");

                    b.HasIndex("CollectionId", "Kind")
                        .HasDatabaseName("ix_collection_views_collection_id_kind");

                    b.HasIndex("DatabaseId", "Position")
                        .HasDatabaseName("ix_collection_views_database_id_position");

                    b.ToTable("collection_views", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Database", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("NodeId")
                        .HasName("pk_databases");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_databases_collection_id");

                    b.ToTable("databases", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<byte[]>("Ydoc")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ydoc");

                    b.HasKey("NodeId")
                        .HasName("pk_documents");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.DocumentUpdate", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<long>("Seq")
                        .HasColumnType("bigint")
                        .HasColumnName("seq");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at");

                    b.Property<byte[]>("Update")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("update");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("NodeId", "Seq")
                        .HasName("pk_document_updates");

                    b.ToTable("document_updates", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Favorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("position");

                    b.HasKey("UserId", "WorkspaceId", "NodeId")
                        .HasName("pk_favorites");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_favorites_node_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_favorites_workspace_id");

                    b.HasIndex("UserId", "WorkspaceId", "Position")
                        .HasDatabaseName("ix_favorites_user_id_workspace_id_position");

                    b.ToTable("favorites", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.ImportJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("file_path");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<Guid?>("ParentNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_node_id");

                    b.Property<JsonElement?>("Result")
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_import_jobs");

                    b.HasIndex("WorkspaceId", "CreatedAt")
                        .HasDatabaseName("ix_import_jobs_workspace_id_created_at");

                    b.ToTable("import_jobs", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Invite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid?>("UsedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("used_by_user_id");

                    b.HasKey("Id")
                        .HasName("pk_invites");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_invites_code");

                    b.ToTable("invites", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Link", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Href")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("href");

                    b.Property<LinkKind>("Kind")
                        .HasColumnType("link_kind")
                        .HasColumnName("kind");

                    b.Property<Guid?>("SourceBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_block_id");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_node_id");

                    b.Property<Guid?>("TargetBlockId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_block_id");

                    b.Property<Guid?>("TargetNodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_node_id");

                    b.HasKey("Id")
                        .HasName("pk_links");

                    b.HasIndex("SourceNodeId")
                        .HasDatabaseName("ix_links_source_node_id");

                    b.HasIndex("TargetBlockId")
                        .HasDatabaseName("ix_links_target_block_id");

                    b.HasIndex("TargetNodeId")
                        .HasDatabaseName("ix_links_target_node_id");

                    b.HasIndex("SourceNodeId", "Kind")
                        .HasDatabaseName("ix_links_source_node_id_kind");

                    b.ToTable("links", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.LinkPreview", b =>
                {
                    b.Property<string>("UrlHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("url_hash");

                    b.Property<JsonElement>("Data")
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("UrlHash")
                        .HasName("pk_link_previews");

                    b.ToTable("link_previews", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<string>("Cover")
                        .HasColumnType("jsonb")
                        .HasColumnName("cover");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Icon")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon");

                    b.Property<NodeKind>("Kind")
                        .HasColumnType("node_kind")
                        .HasColumnName("kind");

                    b.Property<string>("PageSettings")
                        .HasColumnType("jsonb")
                        .HasColumnName("page_settings");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("position");

                    b.Property<JsonElement?>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_nodes");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_nodes_parent_id");

                    b.HasIndex("Properties")
                        .HasDatabaseName("ix_nodes_properties");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Properties"), "gin");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_nodes_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.HasIndex("WorkspaceId", "CollectionId")
                        .HasDatabaseName("ix_nodes_workspace_id_collection_id");

                    b.HasIndex("WorkspaceId", "DeletedAt")
                        .HasDatabaseName("ix_nodes_workspace_id_deleted_at");

                    b.HasIndex("WorkspaceId", "ParentId", "Position")
                        .HasDatabaseName("ix_nodes_workspace_id_parent_id_position");

                    b.ToTable("nodes", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.NodeShare", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<WorkspaceRole>("Role")
                        .HasColumnType("workspace_role")
                        .HasColumnName("role");

                    b.HasKey("NodeId", "UserId")
                        .HasName("pk_node_shares");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_node_shares_user_id");

                    b.ToTable("node_shares", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.NodeTag", b =>
                {
                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("tag_id");

                    b.Property<TagSource>("Source")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tag_source")
                        .HasDefaultValue(TagSource.Manual)
                        .HasColumnName("source");

                    b.HasKey("NodeId", "TagId", "Source")
                        .HasName("pk_node_tags");

                    b.HasIndex("TagId")
                        .HasDatabaseName("ix_node_tags_tag_id");

                    b.HasIndex("NodeId", "Source")
                        .HasDatabaseName("ix_node_tags_node_id_source");

                    b.ToTable("node_tags", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_events_outbox");

                    b.HasIndex("DispatchedAt")
                        .HasDatabaseName("ix_events_outbox_pending")
                        .HasFilter("dispatched_at IS NULL");

                    b.ToTable("events_outbox", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.PageSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BlockCount")
                        .HasColumnType("integer")
                        .HasColumnName("block_count");

                    b.Property<JsonElement>("Blocks")
                        .HasColumnType("jsonb")
                        .HasColumnName("blocks");

                    b.Property<SnapshotKind>("Kind")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("snapshot_kind")
                        .HasDefaultValue(SnapshotKind.Auto)
                        .HasColumnName("kind");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("TakenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_page_snapshots");

                    b.HasIndex("NodeId", "Kind")
                        .HasDatabaseName("ix_page_snapshots_node_id_kind");

                    b.HasIndex("NodeId", "TakenAt")
                        .HasDatabaseName("ix_page_snapshots_node_id_taken_at");

                    b.ToTable("page_snapshots", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.PluginState", b =>
                {
                    b.Property<string>("PluginId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plugin_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<JsonElement>("Value")
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("PluginId", "Key")
                        .HasName("pk_plugin_state");

                    b.ToTable("plugin_state", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Recent", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("node_id");

                    b.Property<DateTimeOffset>("VisitedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visited_at");

                    b.HasKey("UserId", "WorkspaceId", "NodeId")
                        .HasName("pk_recents");

                    b.HasIndex("NodeId")
                        .HasDatabaseName("ix_recents_node_id");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ix_recents_workspace_id");

                    b.HasIndex("UserId", "WorkspaceId", "VisitedAt")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_recents_user_id_workspace_id_visited_at");

                    b.ToTable("recents", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("instance")
                        .HasColumnName("scope");

                    b.Property<Guid>("ScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000000"))
                        .HasColumnName("scope_id");

                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<JsonElement>("Value")
                        .HasColumnType("jsonb")
                        .HasColumnName("value");

                    b.HasKey("Scope", "ScopeId", "Key")
                        .HasName("pk_settings");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("color");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("WorkspaceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_workspace_id_name");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsInstanceOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("is_instance_owner");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("TotpSecret")
                        .HasColumnType("text")
                        .HasColumnName("totp_secret");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Workspace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Icon")
                        .HasColumnType("jsonb")
                        .HasColumnName("icon");

                    b.Property<bool>("IsPersonal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_personal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id")
                        .HasName("pk_workspaces");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_workspaces_owner_id");

                    b.ToTable("workspaces", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.WorkspaceMember", b =>
                {
                    b.Property<Guid>("WorkspaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("workspace_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<WorkspaceRole>("Role")
                        .HasColumnType("workspace_role")
                        .HasColumnName("role");

                    b.HasKey("WorkspaceId", "UserId")
                        .HasName("pk_workspace_members");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_workspace_members_user_id");

                    b.ToTable("workspace_members", (string)null);
                });

            modelBuilder.Entity("Nook.Domain.Entities.Alias", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_aliases_nodes_node_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.ApiToken", b =>
                {
                    b.HasOne("Nook.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_api_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Blob", null)
                        .WithMany()
                        .HasForeignKey("BlobSha")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_blobs_blob_sha");

                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_nodes_node_id");

                    b.HasOne("Nook.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attachments_workspaces_workspace_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Block", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocks_nodes_node_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Collection", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collections_workspaces_workspace_id");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nook.Domain.Entities.CollectionView", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_collection_views_collections_collection_id");

                    b.HasOne("Nook.Domain.Entities.Database", "Database")
                        .WithMany("Views")
                        .HasForeignKey("DatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_collection_views_databases_database_id");

                    b.Navigation("Collection");

                    b.Navigation("Database");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Database", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Collection", "Collection")
                        .WithMany("Databases")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_databases_collections_collection_id");

                    b.HasOne("Nook.Domain.Entities.Node", "Node")
                        .WithOne()
                        .HasForeignKey("Nook.Domain.Entities.Database", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_databases_nodes_node_id");

                    b.Navigation("Collection");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Document", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", "Node")
                        .WithOne()
                        .HasForeignKey("Nook.Domain.Entities.Document", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_nodes_node_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Nook.Domain.Entities.DocumentUpdate", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_updates_nodes_node_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Favorite", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_nodes_node_id");

                    b.HasOne("Nook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_users_user_id");

                    b.HasOne("Nook.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_favorites_workspaces_workspace_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Nook.Domain.Entities.ImportJob", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_import_jobs_workspaces_workspace_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Link", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_links_nodes_source_node_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Node", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_nodes_nodes_parent_id");

                    b.HasOne("Nook.Domain.Entities.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_nodes_workspaces_workspace_id");

                    b.Navigation("Parent");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nook.Domain.Entities.NodeShare", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", "Node")
                        .WithMany("Shares")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_shares_nodes_node_id");

                    b.HasOne("Nook.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_shares_users_user_id");

                    b.Navigation("Node");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nook.Domain.Entities.NodeTag", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_tags_nodes_node_id");

                    b.HasOne("Nook.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_node_tags_tags_tag_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.PageSnapshot", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", null)
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_page_snapshots_nodes_node_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Recent", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Node", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recents_nodes_node_id");

                    b.HasOne("Nook.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recents_users_user_id");

                    b.HasOne("Nook.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recents_workspaces_workspace_id");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Tag", b =>
                {
                    b.HasOne("Nook.Domain.Entities.Workspace", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tags_workspaces_workspace_id");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Workspace", b =>
                {
                    b.HasOne("Nook.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_workspaces_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nook.Domain.Entities.WorkspaceMember", b =>
                {
                    b.HasOne("Nook.Domain.Entities.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_users_user_id");

                    b.HasOne("Nook.Domain.Entities.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_workspace_members_workspaces_workspace_id");

                    b.Navigation("User");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Collection", b =>
                {
                    b.Navigation("Databases");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Database", b =>
                {
                    b.Navigation("Views");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Node", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Shares");
                });

            modelBuilder.Entity("Nook.Domain.Entities.User", b =>
                {
                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Nook.Domain.Entities.Workspace", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
