namespace Nook.Plugin.Ai;

public interface IAiProvider
{
    string Id { get; }
    string Name { get; }
    Task<AiProviderResponse> GenerateAsync(AiProviderRequest request, CancellationToken cancellationToken);
}

public interface IAiProviderRegistry
{
    IAiProvider? Find(string id);
}

public sealed class AiProviderRegistry(IEnumerable<IAiProvider> providers) : IAiProviderRegistry
{
    private readonly IReadOnlyDictionary<string, IAiProvider> _providers = providers
        .GroupBy(p => p.Id, StringComparer.OrdinalIgnoreCase)
        .ToDictionary(g => g.Key, g => g.Single(), StringComparer.OrdinalIgnoreCase);

    public IAiProvider? Find(string id) => _providers.GetValueOrDefault(id);
}

/// <summary>
/// Deterministic local provider used only by this package's development and unit tests.
/// It is intentionally not registered by <see cref="AiPlugin"/> and is not an installation preset.
/// </summary>
public sealed class MockAiProvider : IAiProvider
{
    public string Id => "mock";
    public string Name => "Local mock provider";

    public Task<AiProviderResponse> GenerateAsync(AiProviderRequest request, CancellationToken cancellationToken)
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (request.Action == AiAction.AutofillProperties)
        {
            var suggestions = request.Properties
                .Select(property => new AiPropertySuggestion(
                    property.Name,
                    property.Type,
                    System.Text.Json.JsonSerializer.SerializeToElement<object?>(property.Type == "checkbox" ? false : "Mock value"),
                    IsFormula: false,
                    Warning: "Generated by the local mock provider."))
                .ToArray();
            return Task.FromResult(new AiProviderResponse([], suggestions));
        }

        var generated = request.Blocks.Select(block => new AiGeneratedBlock(block.Id, GenerateText(request, block.Text))).ToArray();
        return Task.FromResult(new AiProviderResponse(generated, []));
    }

    private static string GenerateText(AiProviderRequest request, string text) => request.Action switch
    {
        AiAction.Continue => string.IsNullOrWhiteSpace(text) ? "Mock continuation." : $"{text}\n\nMock continuation.",
        AiAction.Rewrite => $"Mock rewrite: {text}",
        AiAction.Shorten => text.Length > 80 ? $"{text[..80].TrimEnd()}…" : $"Mock shortened: {text}",
        AiAction.Translate => $"Mock translation ({request.TargetLanguage ?? "target"}): {text}",
        AiAction.CustomPrompt => $"Mock response: {text}",
        _ => text,
    };
}
